package zairus.iskalliumreactors.blockentity;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import net.neoforged.neoforge.energy.IEnergyStorage;
import zairus.iskalliumreactors.IRConfig;
import zairus.iskalliumreactors.block.ModBlocks;
import zairus.iskalliumreactors.IskalliumReactors;
import net.neoforged.neoforge.capabilities.Capabilities;

/**
 * The output side of a reactor: stores energy generated by the controller and exposes
 * it through the standard IEnergyStorage capability so other mods can draw from it.
 */
public class BlockEntityIRPowerTap extends BlockEntity implements IEnergyStorage
{
    public int energy = 0;
    public int capacity = 1000000;
    public int maxReceive = 0;
    public int maxExtract = 1000;
    public int lastTransferred = 0;

    private int transferredThisTick = 0;

    private BlockEntityIRController controller;

    public BlockEntityIRPowerTap(BlockPos pos, BlockState state)
    {
        super(ModBlockEntities.IR_POWER_TAP.get(), pos, state);
    }

    public void setController(BlockEntityIRController c)
    {
        this.controller = c;
    }

public static void tick(Level level, BlockPos pos, BlockState state, BlockEntityIRPowerTap be)
{
    if (level.isClientSide) return;

    be.transferredThisTick = 0;
    be.capacity = IRConfig.powerTapCapacity;

    int reactorYield = (be.controller != null && be.controller.getIsValidReactor())
            ? be.controller.getCoreCount() * IRConfig.eachIskalliumBlockPowerValue
            : 0;

    // Dynamic maxExtract
    be.maxExtract = reactorYield + IRConfig.powerTapBaseTransferRate;

    // Add production
    if (reactorYield > 0 && be.energy < be.capacity) {
        be.energy = Math.min(be.capacity, be.energy + reactorYield);
    }

    // Controller validity
    if (be.controller != null && level.getBlockState(be.controller.getBlockPos()).getBlock() != ModBlocks.STEEL_CONTROLLER.get()) {
        be.energy = 0;
        be.controller = null;
    }

    // Push using capability
    int maxPush = Math.min(be.energy, be.maxExtract);
    if (maxPush <= 0) {
        be.lastTransferred = 0;
        return;
    }

    int totalPushed = 0;

    for (Direction dir : Direction.values()) {
        if (maxPush <= 0) break;

        BlockPos nPos = pos.relative(dir);
        BlockEntity neighborBE = level.getBlockEntity(nPos);

        if (neighborBE == null || neighborBE instanceof BlockEntityIRController) continue;

        IEnergyStorage storage = level.getCapability(Capabilities.EnergyStorage.BLOCK, nPos, dir.getOpposite());
        if (storage != null && storage.canReceive()) {
            int extracted = be.extractEnergy(maxPush, false);
            int received = storage.receiveEnergy(extracted, false);

            totalPushed += received;

            if (received < extracted) {
                be.energy += (extracted - received);
                be.transferredThisTick -= (extracted - received);
            }

            maxPush -= received;
        }
    }

    be.lastTransferred = totalPushed;
}

    @Override
    protected void loadAdditional(CompoundTag tag, net.minecraft.core.HolderLookup.Provider registries)
    {
        if (tag.contains("IR_EnergyStored"))
            this.energy = tag.getInt("IR_EnergyStored");

        super.loadAdditional(tag, registries);
    }

    @Override
    protected void saveAdditional(CompoundTag tag, net.minecraft.core.HolderLookup.Provider registries)
    {
        super.saveAdditional(tag, registries);

        tag.putInt("IR_EnergyStored", this.energy);
    }

    @Override
    public int extractEnergy(int maxExtract, boolean simulate)
    {
        int amount = Math.min(maxExtract, this.energy);

        if (!simulate)
        {
            this.energy -= amount;
            if (this.energy < 0)
                this.energy = 0;

            this.transferredThisTick += amount;
        }

        return amount;
    }

    @Override
    public int receiveEnergy(int maxReceive, boolean simulate)
    {
        return 0;
    }

    @Override
    public int getEnergyStored()
    {
        return this.energy;
    }

    @Override
    public int getMaxEnergyStored()
    {
        return this.capacity;
    }

    @Override
    public boolean canExtract()
    {
        return true;
    }

    @Override
    public boolean canReceive()
    {
        return false;
    }
}
